# Configuration for git-cliff (used in changelog.yml)
# Minimal, conventional commits based.

[changelog]
header = "# Changelog\n"

[git]
conventional_commits = true
filter_unconventional = false

[output]
# Keep existing content and prepend
prepend = true

# Note:
# - Kein [remote]-Block nötig: git-cliff leitet die URL automatisch vom Git-Remote 'origin' ab
#   (im GitHub Action-Run durch actions/checkout vorhanden).
# - owner/repository sind nicht erforderlich und wurden entfernt, damit Links korrekt generiert werden.
